name: List Branches
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run git command 1
        run: git status

      - name: Run git command 2
        run: |
          msg=$(
            git for-each-ref \
              --sort=author refs/ \
              --format='%(refname:lstrip=3) %(committerdate:raw) %(authorname) %(authordate:iso)' \
              | awk "\$2 < $(date -d "-120 day" "+%s") {print(\$1,\$4,\$5)}"
          )
          echo "$msg"
